### PR TITLE
Add Lua test

### PR DESCRIPTION
**Pull request by daurnimator**
Using [lua-http](https://github.com/daurnimator/lua-http/)

### CODE REVIEW

**Comment by JackOfMostTrades** [comment]
This is perfect. Thanks!

**Comment by daurnimator** [comment]
Interesting... looking at the archived results you uploaded at https://github.com/Netflix/bettertls/commit/a1447c25c5a2ae43b9af7f662bd82932e5232e4d the status of *all* of them is ERROR.
Did things not get run correctly somehow?

You can check the error like so:
```
diff --git a/testsuites/lua_test.lua b/testsuites/lua_test.lua
index 3795703..242a777 100755
--- a/testsuites/lua_test.lua
+++ b/testsuites/lua_test.lua
@@ -42,7 +42,8 @@ local request = http_request.new_from_uri(uri)
 -- Create TLS context with certificate store containing a single trusted root cert
 request.ctx = http_tls.new_client_context()
 request.ctx:setStore(ossl_store.new():add("../certificates/root.crt"))
-local headers = request:go()
+local headers, err = request:go()
+print(err)
 if not headers or headers:get ":status" ~= "200" then
        return os.exit(1)
 end
```

**Comment by JackOfMostTrades** [comment]
Yep, looks like I wasn't paying close enough attention. With your suggestion I see this on the CLI:

    $ lua lua_test.lua https://test.nameconstraints.bettertls.com:8973/well-known.txt
    http.h1_stream{connection=http.h1_connection{type="client";version=1.1};state="half closed (local)"}

That particular endpoint should be a good test since it has the proper name in the CN and SAN and has no name constraints extension. Compare with curl:

    $ curl --cacert ../certificates/root.crt https://test.nameconstraints.bettertls.com:8973/well-known.txt
    OK

Any idea on what should be patched to fix this?

**Comment by daurnimator** [comment]
That output you pasted is a success. What was the exit code?

More detailed debugging code:

```lua
local headers, err = request:go()
if not headers then -- request failed, e.g. server uncontactable, error message is in `err`
    print(err)
else
    headers:dump() -- dump list of headers to console (including status)
end
```

**Comment by JackOfMostTrades** [comment]
Looks like there was a bug in runner.js that was pointing test urls to the wrong place. (I think I refactored the intended test URL at some point and must have missed that one.) It actually hit the python test results as well, so I reran lua and python and updated the archived results. Lua passes 100%! (Incidentally, python has the recurring issue of not applying IP constraints to the CN when the CN is an IP.)

**Comment by daurnimator** [comment]
Great :)

**Comment by daurnimator** [comment]
Minor thing: in the archived results drop down, the lua entry doesn't mention the openssl version.
IIRC, using an IP isn't supported in openssl 0.9.8 (which is what Apple ship in OSX), so it's worth mentioning the openssl version.

**Comment by JackOfMostTrades** [comment]
Oh yea, sure thing. I actually didn't realize that the number at the end of the useragent string was the openssl version. I tweaked that useragent string to use the human-readable luaossl.SSLEAY_VERSION version string and stuck that in the drop-down as well.

**Comment by daurnimator** [comment]
> luaossl.SSLEAY_VERSION

That is the openssl version it was *compiled* against.
`luaossl.version()` is the version it's running with.

Usually they're the same, but sometimes they are different :)

**Comment by daurnimator** [comment]
> That is the openssl version it was compiled against.
> luaossl.version() is the version it's running with.

Oops sorry that was wrong. Ignore that comment.

**Pull request merged**
